# Generated by Django 3.1.3 on 2023-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('plan_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('is_cancel_able', models.BooleanField(default=False, help_text='Is the data plan cancleable', verbose_name='is cancleable data plan')),
            ],
        ),
        migrations.CreateModel(
            name='Purches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plan_started', models.DateTimeField(auto_now_add=True)),
                ('data_plan_ended', models.DateTimeField(blank=True, null=True)),
                ('active_plan', models.BooleanField(default=False, help_text='active plan', verbose_name='active plan')),
            ],
        ),
    ]
