# Generated by Django 3.1.3 on 2023-01-17 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purches',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='user.company'),
        ),
        migrations.AddField(
            model_name='purches',
            name='data_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_plan', to='dataplan.dataplan'),
        ),
        migrations.AddField(
            model_name='purches',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
