# Generated by Django 3.1.3 on 2023-01-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataplan', '0002_auto_20230117_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataplan',
            old_name='duration',
            new_name='duration_in_month',
        ),
    ]
